/**
 * Spotify playlist: https://open.spotify.com/playlist/6RaWRoHnbblmYwyGVdmSoy
 * Bitconnect: https://www.youtube.com/watch?v=e5nyQmaq4k4
 * Operating System Song: https://www.youtube.com/watch?v=FGwevyxoycw
 **/

#include <stdlib.h>
#include "songs.h"

const char* NEVER_GONNA_GIVE_YOU_UP[56] = {
    "We're no strangers to love\n",
    "You know the rules and so do I\n",
    "A full commitment's what I'm thinking of\n",
    "You wouldn't get this from any other guy\n",
    "I just wanna tell you how I'm feeling\n",
    "Gotta make you understand\n",
    "Never gonna give you up\n",
    "Never gonna let you down\n",
    "Never gonna run around and desert you\n",
    "Never gonna make you cry\n",
    "Never gonna say goodbye\n",
    "Never gonna tell a lie and hurt you\n",
    "We've known each other for so long\n",
    "Your heart's been aching but you're too shy to say it\n",
    "Inside we both know what's been going on\n",
    "We know the game and we're gonna play it\n",
    "And if you ask me how I'm feeling\n",
    "Don't tell me you're too blind to see\n",
    "Never gonna give you up\n",
    "Never gonna let you down\n",
    "Never gonna run around and desert you\n",
    "Never gonna make you cry\n",
    "Never gonna say goodbye\n",
    "Never gonna tell a lie and hurt you\n",
    "Never gonna give you up\n",
    "Never gonna let you down\n",
    "Never gonna run around and desert you\n",
    "Never gonna make you cry\n",
    "Never gonna say goodbye\n",
    "Never gonna tell a lie and hurt you\n",
    "Never gonna give, never gonna give\n",
    "(Give you up)\n",
    "(Ooh) Never gonna give, never gonna give\n",
    "(Give you up)\n",
    "We've known each other for so long\n",
    "Your heart's been aching but you're too shy to say it\n",
    "Inside we both know what's been going on\n",
    "We know the game and we're gonna play it\n",
    "I just wanna tell you how I'm feeling\n",
    "Gotta make you understand\n",
    "Never gonna give you up\n",
    "Never gonna let you down\n",
    "Never gonna run around and desert you\n",
    "Never gonna make you cry\n",
    "Never gonna say goodbye\n",
    "Never gonna tell a lie and hurt you\n",
    "Never gonna give you up\n",
    "Never gonna let you down\n",
    "Never gonna run around and desert you\n",
    "Never gonna make you cry\n",
    "Never gonna say goodbye\n",
    "Never gonna tell a lie and hurt you\n",
    "Never gonna give you up\n",
    "Never gonna let you down\n",
    "Never gonna run around and desert you\n",
    "Never gonna make you cry\n"
};

const char* WHO_LET_THE_DOGS_OUT[79] = {
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"The party was nice the party was pumping\n",
	"Ah yepee ah yo\n",
	"And everybody having a ball\n",
	"Yepee ah yo\n",
	"And tell the fellas stop the name callin'\n",
	"Yepee ah yo\n",
	"Then them girls respond to the call\n",
	"I hear a woman shout outâ?¦\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Last year in the dance you had a ball\n",
	"You call me millibug and skettell\n",
	"Get back gruffy, mash scruffy\n",
	"Get back you flea infested mongrel\n",
	"V3\n",
	"Now I tell meh self dem man go get angry\n",
	"Ah yepee ah yo\n",
	"To hear dem girls calling them canine\n",
	"Yepee ah yo\n",
	"But they say hey man dat is part of the party\n",
	"Ah yepee ah yo\n",
	"Them woman in front and they man behind\n",
	"I hear ah woman shout outâ?¦\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"A doggie is nothing if he don't have a bone\n",
	"All doggie hold it\n",
	"Ah doggie is nothing if he don't have a bone\n",
	"All doggie hold it\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Last year in the dance you had a ball\n",
	"You call me millibug and skettell\n",
	"Get back fluffy, back scruffy\n",
	"Get back you flea infested mongrel\n",
	"If I was a dog\n",
	"The party is on\n",
	"I got to get my groove on\n",
	"'cause my mind done gone\n",
	"Can't you see the rays coming from my eyes\n",
	"Walking through the place like digi-man\n",
	"Breaking it down\n",
	"Me and my white tail\n",
	"Short coat\n",
	"Can't see color\n",
	"Any color will do\n",
	"I'll stick on you\n",
	"That's why they call me pit bull\n",
	"'cause I'm the man of the land when they see me\n",
	"They say oooooh\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n",
	"Woof, woof, woof, woof, woof\n",
	"Who let the dogs out\n"
};

const char* WHAT_IS_LOVE[69] = {
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"Baby don't hurt me, don't hurt me\n",
	"No more\n",
	"What is love?\n",
	"Yeah\n",
	"I don't know why you're not fair\n",
	"I give you my love, but you don't care\n",
	"So what is right and what is wrong?\n",
	"Gimme a sign\n",
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"Oh, I don't know, what can I do?\n",
	"What else can I say, it's up to you\n",
	"I know we're one, just me and you\n",
	"I can't go on\n",
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"What is love?\n",
	"What is love?\n",
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"Don't hurt me\n",
	"Don't hurt me\n",
	"I want no other, no other lover\n",
	"This is our life, our time\n",
	"We are together I need you forever\n",
	"Is it love?\n",
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"Yeah, yeah, (woah-woah-woah, oh, oh)\n",
	"(Woah-woah-woah, oh, oh)\n",
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"What is love?\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"Baby don't hurt me\n",
	"Don't hurt me\n",
	"No more\n",
	"What is love?\n"
};

const char* MAJOR_TOM[61] = {
	"Gründlich durchgecheckt steht sie da\n",
	"Und wartet auf den Start - alles klar!\n",
	"Experten streiten sich um ein paar Daten\n",
	"Die Crew hat da noch ein paar Fragen\n",
	"Doch - der Countdown läuft\n",
	"\n",
	"Effektivität bestimmt das Handeln\n",
	"Man verlässt sich blind auf den ander'n\n",
	"Jeder weiß genau, was von ihm abhängt\n",
	"Jeder ist im Stress, doch Major Tom\n",
	"Macht einen Scherz\n",
	"Dann hebt er ab und\n",
	"\n",
	"Völlig losgelöst\n",
	"Von der Erde\n",
	"Schwebt das Raumschiff\n",
	"Völlig schwerelos\n",
	"\n",
	"\n",
	"Die Erdanziehungskraft ist überwunden\n",
	"Alles läuft perfekt, schon seit Stunden\n",
	"Wissenschaftliche Experimente\n",
	"Doch was nützen die am Ende, denkt\n",
	"Sich Major Tom\n",
	"\n",
	"Im Kontrollzentrum, da wird man panisch\n",
	"Der Kurs der Kapsel, der stimmt ja gar nicht\n",
	"\"Hallo Major Tom, können Sie hören\n",
	"Woll'n Sie das Projekt denn so zerstören?\"\n",
	"Doch er kann nichts hör'n\n",
	"Er schwebt weiter\n",
	"\n",
	"Völlig losgelöst\n",
	"Von der Erde\n",
	"Schwebt das Raumschiff\n",
	"Völlig schwerelos\n",
	"\n",
	"Die Erde schimmert blau, sein letzter Funk kommt\n",
	"\"Grüßt mir meine Frau\", und er verstummt\n",
	"\n",
	"Unten trauern noch die Egoisten\n",
	"Major Tom denkt sich, wenn die wüssten\n",
	"Mich führt hier ein Licht durch das All\n",
	"Das kennt ihr noch nicht, ich komme bald\n",
	"Mir wird kalt\n",
	"\n",
	"\n",
	"Völlig losgelöst\n",
	"Von der Erde\n",
	"Schwebt das Raumschiff\n",
	"Schwerelos\n",
	"\n",
	"Völlig losgelöst\n",
	"Von der Erde\n",
	"Schwebt das Raumschiff\n",
	"Schwerelos\n",
	"\n",
	"Völlig losgelöst\n",
	"Von der Erde\n",
	"Schwebt das Raumschiff\n",
	"Völlig schwerelos\n"
};

const char* LOOKING_FOR_FREEDOM[52] = {
	"One morning in June\n",
	"some twenty years ago\n",
	"I was born a rich man's son\n",
	"I had everything that money could buy,\n",
	"but freedom I had none\n",
	"I've been looking for freedom\n",
	"I've been looking so long\n",
	"I've been looking for freedom\n",
	"Still the search goes on\n",
	"I've been looking for freedom\n",
	"since I left my home town\n",
	"I've been looking for freedom\n",
	"Still it can't be found\n",
	"I headed down the track\n",
	"my baggage on my back\n",
	"I left the city far behind\n",
	"Walking down that road\n",
	"with my heavy load\n",
	"trying to find some ease of mind\n",
	"Father said: \"You'll be sorry, son,\n",
	"if you leave your home this way\n",
	"And when you realize\n",
	"the freedom money buys\n",
	"You'll come running home someday\"\n",
	"I've been looking for freedom\n",
	"I've been looking so long\n",
	"I've been looking for freedom\n",
	"Still the search goes on\n",
	"I've been looking for freedom\n",
	"Since I left my home town\n",
	"I've been looking for freedom\n",
	"Still it can't be found\n",
	"I made a lot of dues\n",
	"had plenty to lose\n",
	"travelling across the land\n",
	"Worked on a farm,\n",
	"got some muscle in my arms\n",
	"but still I'm not a self-made man\n",
	"I feel the run for many years to come\n",
	"I'll be searching door to door\n",
	"And given some time\n",
	"some day I'm gonna find\n",
	"the freedom (freedom, freedom) I've been searching for\n",
	"I've been looking for freedom\n",
	"I've been looking so long\n",
	"I've been looking for freedom\n",
	"Still the search goes on\n",
	"I've been looking for freedom\n",
	"Since I left my home town\n",
	"I've been looking for freedom\n",
	"Still it can't be found\n",
	"Still it can't be found\n"
};

const char* SKANDAL_IM_SPERRBEZIRK[56] = {
	"Spider Murphy Gang\n",
	"Ihre Größten Erfolge\n",
	"Skandal Im Sperrbezirk\n",
	"In München steht ein Hofbräuhaus\n",
	"doch Freudenhäuser müssen raus,\n",
	"damit in dieser schönen Stadt\n",
	"das Laster keine Chance hat!\n",
	"Doch jeder ist gut informiert\n",
	"weil Rosie täglich inseriert\n",
	"und wenn dich deine Frau nicht liebt\n",
	"wie gut, daß es die Rosi gibt!\n",
	"Und draußen vor der großen Stadt\n",
	"stehen die Nutten sich die Füße platt!\n",
	"Skandal (Skandal)\n",
	"im Sperrbezirk\n",
	"Skandal (Skandal)\n",
	"im Sperrbezirk\n",
	"Skandal\n",
	"Skandal um Rosie!\n",
	"Ja Rosie hat ein Telefon\n",
	"auch ich hab' ihre Nummer schon.\n",
	"Unter 32-16-8\n",
	"herrscht Konjunktur die ganze Nacht.\n",
	"Und draußen im Hotel d'Amour\n",
	"langweilen sich die Damen nur,\n",
	"weil jeder den die Sehnsucht quält\n",
	"ganz einfach Rosies Nummer wählt.\n",
	"Und draußen vor der großen Stadt\n",
	"stehen die Nutten sich die Füße platt!\n",
	"im Sperrbezirk\n",
	"Skandal (Skandal)\n",
	"im Sperrbezirk\n",
	"Skandal\n",
	"Skandal um Rosie!\n",
	"Ja Rosie hat ein Telefon\n",
	"auch ich hab' ihre Nummer schon.\n",
	"Unter 32-16-8\n",
	"herrscht Konjunktur die ganze Nacht.\n",
	"Und draußen im Hotel d'Amour\n",
	"langweilen sich die Damen nur,\n",
	"weil jeder den die Sehnsucht quält\n",
	"ganz einfach Rosies Nummer wählt.\n",
	"Und draußen vor der großen Stadt\n",
	"stehen die Nutten sich die Füße platt!\n",
	"Skandal (Skandal)\n",
	"im Sperrbezirk\n",
	"Skandal (Skandal)\n",
	"im Sperrbezirk\n",
	"Skandal\n",
	"Skandal um Rosie!\n",
	"Moral\n",
	"Skandal\n",
	"Moral\n",
	"Skandal\n",
	".\n",
	"Skandal um Rosie!\n"
};

const char* DANGER_ZONE[34] = {
	"Revvin' up your engine\n",
	"Listen to her howlin' roar\n",
	"Metal under tension\n",
	"Beggin' you to touch and go\n",
	"Highway to the danger zone\n",
	"Ride into the danger zone\n",
	"Headin' into twilight\n",
	"Spreadin' out her wings tonight\n",
	"She got you jumpin' off the track\n",
	"And shovin' into overdrive\n",
	"Highway to the danger zone\n",
	"I'll take you\n",
	"Ridin' into the danger zone\n",
	"You'll never say hello to you\n",
	"Until you get it on the red line overload\n",
	"You'll never know what you can do\n",
	"Until you get it up as high as you can go\n",
	"Out along the edges\n",
	"Always where I burn to be\n",
	"The further on the edge\n",
	"The hotter the intensity\n",
	"Highway to the danger zone\n",
	"Gonna take you\n",
	"Right into the danger zone\n",
	"Highway to the danger zone\n",
	"Right into the danger zone\n",
	"Highway to the danger zone\n",
	"Gonna take you right into the danger zone\n",
	"Highway to the danger zone\n",
	"Right into the danger zone\n",
	"Highway to the danger zone\n",
	"Gonna take you right into the danger zone\n",
	"Highway to the danger zone\n",
	"Right into the danger zone\n"
};

const char* SCATMAN[98] = {
	"I'm the Scatman\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"(I'm the Scatman)\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Ba-da-ba-da-ba-be bop bop bodda bope\n",
	"Bop ba bodda bope\n",
	"Be bop ba bodda bope\n",
	"Bop ba bodda\n",
	"Ba-da-ba-da-ba-be bop ba bodda bope\n",
	"Bop ba bodda bope\n",
	"Be bop ba bodda bope\n",
	"Bop ba bodda bope\n",
	"Everybody stutters one way or the other\n",
	"So check out my message to you\n",
	"As a matter of fact, I don't let nothin' hold you back\n",
	"If the Scatman can do it, so can you\n",
	"Everybody's sayin' that the Scatman stutters\n",
	"But doesn't ever stutter when he sings\n",
	"But what you don't know, I'm gonna tell you right now\n",
	"That the stutter and the scat is the same thing\n",
	"Yo, I'm the Scatman\n",
	"Where's the Scatman?\n",
	"I'm the Scatman\n",
	"Why should we be pleasin' all the politician heathens\n",
	"Who would try to change the seasons if they could?\n",
	"The state of the condition insults my intuition\n",
	"And it only makes me crazy and a heart like wood\n",
	"Everybody stutters one way or the other\n",
	"So check out my message to you\n",
	"As a matter of fact, don't let nothin' hold you back\n",
	"If the Scatman can do it, brother, so can you\n",
	"I'm the Scatman\n",
	"Ba-da-ba-da-ba-be bop bop bodda bope\n",
	"Bop ba bodda bope\n",
	"Be bop ba bodda bope\n",
	"Bop ba bodda\n",
	"Ba-da-ba-da-ba-be bop ba bodda bope\n",
	"Bop ba bodda bope\n",
	"Be bop ba bodda bope\n",
	"Bop ba bodda bope\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Everybody stutters one way or the other\n",
	"So check out my message to you\n",
	"As a matter of fact, I don't let nothin' hold you back\n",
	"If the Scatman can do it, so can you\n",
	"I hear you all ask 'bout the meaning of scat\n",
	"Well, I'm the professor and all I can tell you is\n",
	"While you're still sleepin', the saints are still weepin' 'cause\n",
	"Things you call dead haven't had the chance to be born\n",
	"I'm the Scatman\n",
	"Ba-da-ba-da-ba-be bop bop bodda bope\n",
	"Bop ba bodda bope\n",
	"Be bop ba bodda bope\n",
	"Bop ba bodda\n",
	"Ba-da-ba-da-ba-be bop ba bodda bope\n",
	"Bop ba bodda bope\n",
	"Be bop ba bodda bope\n",
	"Bop ba bodda bope\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"Yo da dub dub\n",
	"Ski-bi dibby dib yo da dub dub\n",
	"yeah, I'm the Scatman\n",
	"Where's the Scatman?\n",
	"I'm the Scatman, repeat after me\n",
	"It's a scoobie oobie doobie, scoobie doobie melody\n",
	"I'm the Scatman, sing along with me\n",
	"It's a scoobie oobie doobie, scoobie doobie melody\n",
	"Yeah, I'm the Scatman, I'm the Scatman\n",
	"Bop ba bodda bope\n",
	"Be bop ba bodda bope\n",
	"Bop ba bodda\n",
	"I'm the Scatman\n",
	"Bop ba bodda bope\n",
	"Be bop ba bodda bope\n",
	"Ba-da-ba-da-ba-be bop bop bodda bope\n",
	"Bop ba bodda bope\n",
	"Be bop ba bodda bope\n",
	"Bop ba bodda\n",
	"Ba-da-ba-da-ba-be bop ba bodda bope (Yeah, I'm the Scatman)\n",
	"Bop ba bodda bope (sing along with me)\n",
	"Be bop ba bodda bope (it's a scoobie oobie doobie, scoobie doobie melody)\n"
};

const char* I_LIKE_TO_MOVE_IT[81] = {
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n",
	"All girls all over the world\n",
	"Original Mad Stuntman 'pon ya case man\n",
	"I love how all the girls are move them body\n",
	"And when ya move ya body\n",
	"Gonna move it nice and sweet, and sexy, alright?\n",
	"Woman ya cute and you don't need no make up\n",
	"Original cute body you a mek man mud up\n",
	"Woman ya cute and you don't need no make up\n",
	"Original cute body you a mek man mud up\n",
	"Woman, physically fit, physically fit\n",
	"Physically, physically, physically\n",
	"Woman, physically fit, physically fit\n",
	"Physically, physically, physically\n",
	"Woman, ya nice, sweet, fantastic\n",
	"Big ship 'pon di ocean that a big Titanic\n",
	"C'mon, ya nice, sweet, I enjoy the thing\n",
	"Big ship 'pon di ocean that a big Titanic\n",
	"Woman, ya nice, sweet, fantastic\n",
	"Big ship 'pon di ocean that a big Titanic\n",
	"C'mon, ya nice, sweet, I enjoy the thing\n",
	"Big ship 'pon di ocean that a big Titanic\n",
	"Woman\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n",
	"Woman ya cute and you don't need no make up\n",
	"Original cute body you a mek man mud up\n",
	"Woman ya cute and you don't need no make up\n",
	"Original cute body you a mek man mud up\n",
	"Eyeliner 'pon ya face a mek man mud up\n",
	"Nose powder 'pon ya face a mek man mud up\n",
	"Pluck ya eyebrow 'pon ya face a mek man mud up\n",
	"Gal ya lipstick 'pon ya face a mek man mud up\n",
	"Woman, ya nice, broad face\n",
	"And ya nice hip\n",
	"Make man flip and bust up them lip\n",
	"Woman, ya nice and energetic\n",
	"Big ship 'pon de ocean that a big Titanic\n",
	"Woman, ya nice, broad face\n",
	"And ya nice hip\n",
	"Make man flip and bust up them lip\n",
	"Woman, ya nice and energetic\n",
	"Big ship 'pon de ocean that a big Titanic\n",
	"Woman\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"I like to move it, move it\n",
	"Ya like to move it\n"
};

const char* TEQUILA[3] = {
	"Tequila\n",
	"Tequila\n",
	"Tequila\n"
};

const char* BARBIE_GIRL[58] = {
	"Hiya, Barbie\n",
	"Hi, Ken!\n",
	"You want to go for a ride?\n",
	"Sure, Ken\n",
	"Jump in\n",
	"I'm a Barbie girl in a Barbie world\n",
	"Life in plastic, it's fantastic\n",
	"You can brush my hair, undress me everywhere\n",
	"Imagination, life is your creation\n",
	"Come on, Barbie, let's go party!\n",
	"I'm a Barbie girl in a Barbie world\n",
	"Life in plastic, it's fantastic\n",
	"You can brush my hair, undress me everywhere\n",
	"Imagination, life is your creation\n",
	"I'm a blond bimbo girl in a fantasy world\n",
	"Dress me up, make it tight, I'm your dolly\n",
	"You're my doll, rock'n'roll, feel the glamour in pink\n",
	"Kiss me here, touch me there, hanky panky\n",
	"You can touch\n",
	"You can play\n",
	"If you say \"I'm always yours\"\n",
	"I'm a Barbie girl in a Barbie world\n",
	"Life in plastic, it's fantastic\n",
	"You can brush my hair, undress me everywhere\n",
	"Imagination, life is your creation\n",
	"Come on, Barbie, let's go party! (ah ah ah yeah)\n",
	"Come on, Barbie, let's go party! (ooh oh, ooh oh)\n",
	"Come on, Barbie, let's go party! (ah ah ah yeah)\n",
	"Come on, Barbie, let's go party! (ooh oh, ooh oh)\n",
	"Make me walk, make me talk, do whatever you please\n",
	"I can act like a star, I can beg on my knees\n",
	"Come jump in, bimbo friend, let us do it again\n",
	"Hit the town, fool around, let's go party\n",
	"You can touch\n",
	"You can play\n",
	"If you say \"I'm always yours\"\n",
	"You can touch\n",
	"You can play\n",
	"If you say \"I'm always yours\"\n",
	"Come on, Barbie, let's go party! (ah ah ah yeah)\n",
	"Come on, Barbie, let's go party! (ooh oh, ooh oh)\n",
	"Come on, Barbie, let's go party! (ah ah ah yeah)\n",
	"Come on, Barbie, let's go party! (ooh oh, ooh oh)\n",
	"I'm a Barbie girl in a Barbie world\n",
	"Life in plastic, it's fantastic\n",
	"You can brush my hair, undress me everywhere\n",
	"Imagination, life is your creation\n",
	"I'm a Barbie girl in a Barbie world\n",
	"Life in plastic, it's fantastic\n",
	"You can brush my hair, undress me everywhere\n",
	"Imagination, life is your creation\n",
	"Come on, Barbie, let's go party! (ah ah ah yeah)\n",
	"Come on, Barbie, let's go party! (ooh oh, ooh oh)\n",
	"Come on, Barbie, let's go party! (ah ah ah yeah)\n",
	"Come on, Barbie, let's go party! (ooh oh, ooh oh)\n",
	"Oh, I'm having so much fun!\n",
	"Well, Barbie, we are just getting started\n",
	"Oh, I love you, Ken\n"
};

const char* DISCO_POGO[51] = {
	"Was ist los? Es ist Party angesagt!\n",
	"Die Saison ist eröffnet, es ist ein wahres Spektakel\n",
	"Denn alle komm'n weil es abgeht\n",
	"Das ist 'ne riesengroße Party\n",
	"Reißt die Arme in den Himmel und schwenkt sie über den Kopf\n",
	"Mann, wir sind erst am Ziel\n",
	"Wenn der Schweiß von der Decke tropft\n",
	"Die Wände schwitzen, alle springen\n",
	"Alles was wir lieben\n",
	"Wir lassen uns das gottverdammte Feiern nicht verbieten\n",
	"Wie ein kranker Haufen raufen wir uns, Atzen lasst es krachen\n",
	"Die Spießer sind geschockt und packen ganz schnell ihre Sachen\n",
	"Wir lassen uns nicht verarschen\n",
	"Wir tanzen und wir toben, hebt die Hände nach oben\n",
	"Und dann lasst uns Disco Pogen\n",
	"Disco Pop\n",
	"Dingelingeling\n",
	"Dingelingeling\n",
	"Und alle Atzen singen\n",
	"Disco Pogo\n",
	"Dingelingeling\n",
	"Dingelingeling\n",
	"Und alle Atzen singen\n",
	"Die Masse rockt, wir sind bekloppte Pogen\n",
	"Stopp und don't stop the rock\n",
	"Wir baden in der Menge\n",
	"Darauf hab ich Bock\n",
	"Voll normal verfeiern mit\n",
	"Ich fass mir auch mal in den Schritt\n",
	"Breakdance, oder Atzentanz\n",
	"Wir tanzen heut' den Pogohit\n",
	"Disco Pogo, Atzenlogo\n",
	"Atzenstyle ist Disco Pogo\n",
	"Atzen rasten nicht am Tag\n",
	"Und feiern mit dem Atzenlogo\n",
	"Schubsen, drücken, hüpfen, springen\n",
	"Raufen, saufen, tanzen, pogen\n",
	"Atzenparty dingeling\n",
	"Atzenparty dingeling\n",
	"Atzenparty dingeling\n",
	"Atzenparty dingeling\n",
	"Disco Pogen unser Ding\n",
	"Disco Pogen unser Ding\n",
	"Disco Pop\n",
	"Dingelingeling\n",
	"Dingelingeling\n",
	"Und alle Atzen singen\n",
	"Disco Pogo\n",
	"Dingelingeling\n",
	"Dingelingeling\n",
	"Und alle Atzen singen\n"
};

const char* CHERI_CHERI_LADY[69] = {
	"Oh, I cannot explain\n",
	"Every time it's the same\n",
	"Oh, I feel that it's real\n",
	"Take my heart\n",
	"I've been lonely too long\n",
	"Oh, I can't be so strong\n",
	"Take a chance for romance\n",
	"Take my heart\n",
	"I need you so\n",
	"There's no time\n",
	"I'll ever go\n",
	"Cheri Cheri Lady\n",
	"Goin' through emotion\n",
	"Love is where you find it\n",
	"Listen to your heart\n",
	"Cheri Cheri Lady\n",
	"Livin' in devotion\n",
	"It's always like the first time\n",
	"Let me take a part\n",
	"Cheri Cheri Lady\n",
	"Like there's no tomorrow\n",
	"Take my heart, don't lose it\n",
	"Listen to your heart\n",
	"Cheri Cheri Lady\n",
	"To know you is to love you\n",
	"If you call me baby\n",
	"I'll be always yours\n",
	"I get up and get down\n",
	"Oh, my world turns around\n",
	"Who is right? Who is wrong?\n",
	"I don't know\n",
	"I've got pain in my heart\n",
	"Got a love in my soul\n",
	"Easy come but I think easy go\n",
	"I need you so\n",
	"All those times\n",
	"I'm not so strong\n",
	"Cheri Cheri Lady\n",
	"Goin' through emotion\n",
	"Love is where you find it\n",
	"Listen to your heart\n",
	"Cheri Cheri Lady\n",
	"Livin' in devotion\n",
	"It's always like the first time\n",
	"Let me take a part\n",
	"Cheri Cheri Lady\n",
	"Like there's no tomorrow\n",
	"Take my heart, don't lose it\n",
	"Listen to your heart\n",
	"Cheri Cheri Lady\n",
	"To know you is to love you\n",
	"If you call me baby\n",
	"I'll be always yours\n",
	"Cheri Cheri Lady\n",
	"Like there's no tomorrow\n",
	"Take my heart, don't lose it\n",
	"Listen to your heart\n",
	"Cheri Cheri Lady\n",
	"To know you is to love you\n",
	"If you call me baby\n",
	"I'll be yours\n",
	"Cheri Cheri Lady\n",
	"Like there's no tomorrow\n",
	"Take my heart, don't lose it\n",
	"Listen to your heart\n",
	"Cheri Cheri Lady\n",
	"To know you is to love you\n",
	"If you call me baby\n",
	"I'll be yours\n"
};

const char* BOOMERANG[61] = {
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer wieder bei dir an\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer näher an dich ran\n",
	"Ich flieg' so schnell ich kann\n",
	"In deine Umlaufbahn\n",
	"Da bleib' ich einfach drauf und irgendwann fängst du mich auf\n",
	"Boom, boom!\n",
	"Boom, boom!\n",
	"Boom, boom!\n",
	"Boom, boom!\n",
	"Boom, boom!\n",
	"So wie ein Boomerang!\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer wieder bei dir an\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer näher an dich ran\n",
	"Ich flieg' so schnell ich kann\n",
	"In deine Umlaufbahn\n",
	"Da bleib' ich einfach drauf und irgendwann fängst du mich auf\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer wieder bei dir an\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer näher an dich ran\n",
	"So wie ein Boomerang! (Boom!)\n",
	"Boom! (Wann fängst du mich)\n",
	"Wann fängst du mich auf?\n",
	"Boom! (Wann fängst du mich)\n",
	"Wann fängst du mich auf?\n",
	"Boom! (Wann fängst du mich)\n",
	"Wann fängst du mich auf?\n",
	"Boom, boom!\n",
	"Boom, boom, boom boom\n",
	"Boom, boom!\n",
	"Boom, boom, boom boom\n",
	"Boom boom boom, baba ba bam bam\n",
	"Wie ein Boomerang komm ich immer wieder bei dir an\n",
	"Boom boom boom, baba ba bam bam\n",
	"Wie ein Boomerang komm ich immer wieder bei dir an\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer wieder bei dir an\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer näher an dich ran\n",
	"Ich flieg' so schnell ich kann\n",
	"In deine Umlaufbahn\n",
	"Da bleib' ich einfach drauf und irgendwann fängst du mich auf\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer wieder bei dir an\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer näher an dich ran\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer wieder bei dir an\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer näher an dich ran\n",
	"Ich flieg' so schnell ich kann\n",
	"In deine Umlaufbahn\n",
	"Da bleib' ich einfach drauf und irgendwann fängst du mich auf\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer wieder bei dir an\n",
	"Wie ein Boom, Boom, Boom, Boom, Boomerang\n",
	"Komm' ich immer näher an dich ran\n"
};

const char* NEUNUNDNEUNZIG_LUFTBALLONS[41] = {
	"You and I in a little toy shop\n",
	"Buy a bag of balloons with the money we've got\n",
	"Set them free at the break of dawn\n",
	"'Til one by one they were gone\n",
	"Back at base bugs in the software\n",
	"Flash the message \"something's out there!\"\n",
	"Floating in the summer sky\n",
	"Ninety-nine red balloons go by\n",
	"Ninety-nine red balloons\n",
	"Floating in the summer sky\n",
	"Panic bells, it's red alert\n",
	"There's something here from somewhere else\n",
	"The war machine springs to life\n",
	"Opens up one eager eye\n",
	"Focusing it on the sky\n",
	"Where ninety-nine red balloons go by\n",
	"Ninety-nine decision street\n",
	"Ninety-nine ministers meet\n",
	"To worry, worry, super scurry\n",
	"Call the troops out in a hurry\n",
	"This is what we've waited for\n",
	"This is it, boys, this is war\n",
	"The president is on the line\n",
	"As ninety-nine red balloons go by\n",
	"Ninety-nine knights of the air\n",
	"Ride super high-tech jet fighters\n",
	"Everyone's a super hero\n",
	"Everyone's a captain Kirk\n",
	"With orders to identify\n",
	"To clarify and classify\n",
	"Scramble in the summer sky\n",
	"Ninety-nine red balloons go by\n",
	"As ninety-nine red balloons go by\n",
	"Ninety-nine dreams I have had\n",
	"In every one a red balloon\n",
	"It's all over and I'm standing pretty\n",
	"In this dust that was a city\n",
	"If I could find a souvenir\n",
	"Just to prove the world was here\n",
	"And here is a red balloon\n",
	"I think of you, and let it go\n"
};

const char* BLUE_DA_BA_DEE[43] = {
	"Yo listen up, here's the story\n",
	"About a little guy that lives in a blue world\n",
	"And all day and all night and everything he sees is just blue\n",
	"Like him, inside and outside\n",
	"Blue his house with a blue little window\n",
	"And a blue Corvette\n",
	"And everything is blue for him\n",
	"And himself and everybody around\n",
	"'Cause he ain't got nobody to listen\n",
	"I'm blue da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"I'm blue da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"I have a blue house with a blue window\n",
	"Blue is the color of all that I wear\n",
	"Blue are the streets and all the trees are too\n",
	"I have a girlfriend and she is so blue\n",
	"Blue are the people here that walk around\n",
	"Blue like my Corvette, it's in and outside\n",
	"Blue are the words I say and what I think\n",
	"Blue are the feelings that live inside me\n",
	"I'm blue da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"I'm blue da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"I have a blue house with a blue window\n",
	"Blue is the color of all that I wear\n",
	"Blue are the streets and all the trees are too\n",
	"I have a girlfriend and she is so blue\n",
	"Blue are the people here that walk around\n",
	"Blue like my Corvette, it's in and outside\n",
	"Blue are the words I say and what I think\n",
	"Blue are the feelings that live inside me\n",
	"I'm blue da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"I'm blue da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n",
	"Da ba dee da ba daa, da ba dee da ba daa, da ba dee da ba daa\n"
};

const char* OCEAN_MAN[18] = {
	"Ocean man, take me by the hand, lead me to the land that you understand\n",
	"Ocean man, the voyage to the corner of the globe is a real trip\n",
	"Ocean man, the crust of a tan man imbibed by the sand\n",
	"Soaking up the thirst of the land\n",
	"Ocean man, can you see through the wonder of amazement at the oberman\n",
	"Ocean man, the crust is elusive when it casts forth to the childlike man\n",
	"Ocean man, the sequence of a life form braised in the sand\n",
	"Soaking up the thirst of the land\n",
	"Ocean man, ocean man\n",
	"Ocean man\n",
	"Ocean man, take me by the hand, lead me to the land that you understand\n",
	"Ocean man, the voyage to the corner of the globe is a real trip\n",
	"Ocean man,…\n",
	"Ocean man, can you see through the wonder of amazement at the oberman\n",
	"Ocean man, the crust is elusive when it casts forth to the childlike man\n",
	"Ocean man, the sequence of a life form braised in the sand\n",
	"Soaking up the thirst of the land\n",
	"Ocean man\n"
};

const char* SHOUT[102] = {
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you\n",
	"Come on\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you\n",
	"Come on\n",
	"In violent times\n",
	"You shouldn't have to sell your soul\n",
	"In black and white\n",
	"They really really ought to know\n",
	"Those one-track minds\n",
	"That took you for a working boy\n",
	"Kiss them goodbye\n",
	"You shouldn't have to jump for joy\n",
	"You shouldn't have to jump for joy\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you\n",
	"Come on\n",
	"They gave you life\n",
	"And in return you gave them hell\n",
	"As cold as ice\n",
	"I hope we live to tell the tale\n",
	"I hope we live to tell the tale\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you\n",
	"Come on\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you\n",
	"Come on\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you\n",
	"Come on\n",
	"And when you've taken down your guard\n",
	"If I could change your mind\n",
	"I'd really love to break your heart\n",
	"I'd really love to break your heart\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without (break your heat)\n",
	"Come on (really love to break your heart)\n",
	"I'm talking to you\n",
	"Come on\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you\n",
	"So come on\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you\n",
	"Come on\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you (they really really ought to know)\n",
	"Come on\n",
	"Shout\n",
	"Shout\n",
	"Let it all out (I'd really love to break your heart)\n",
	"These are the things I can do without\n",
	"(I'd really love to break your heart)\n",
	"Come on\n",
	"I'm talking to you\n",
	"So come on\n",
	"Shout\n",
	"Shout\n",
	"Let it all out\n",
	"These are the things I can do without\n",
	"Come on\n",
	"I'm talking to you\n"
};

const char* I_M_GONNA_BE_500_MILES[59] = {
	"When I wake up, well I know I'm gonna be,\n",
	"I'm gonna be the man who wakes up next you\n",
	"When I go out, yeah I know I'm gonna be\n",
	"I'm gonna be the man who goes along with you\n",
	"If I get drunk, well I know I'm gonna be\n",
	"I'm gonna be the man who gets drunk next to you\n",
	"And if I haver up, yeah I know I'm gonna be\n",
	"I'm gonna be the man who's havering to you\n",
	"But I would walk 500 miles\n",
	"And I would walk 500 more\n",
	"Just to be the man who walks a thousand miles\n",
	"To fall down at your door\n",
	"When I'm working, yes I know I'm gonna be\n",
	"I'm gonna be the man who's working hard for you\n",
	"And when the money, comes in for the work I do\n",
	"I'll pass almost every penny on to you\n",
	"When I come home (when I come home) well I know I'm gonna be\n",
	"I'm gonna be the man who comes back home to you\n",
	"And if I grow-old (when I grow-old) well I know I'm gonna be\n",
	"I'm gonna be the man who's growing old with you\n",
	"But I would walk 500 miles\n",
	"And I would walk 500 more\n",
	"Just to be the man who walks a thousand miles\n",
	"To fall down at your door\n",
	"Da da da (da da da)\n",
	"Da da da (da da da)\n",
	"Da da da dun diddle un diddle un diddle uh da\n",
	"Da da da (da da da)\n",
	"Da da da (da da da)\n",
	"Da da da dun diddle un diddle un diddle uh da\n",
	"When I'm lonely, well I know I'm gonna be\n",
	"I'm gonna be the man who's lonely without you\n",
	"And when I'm dreaming, well I know I'm gonna dream\n",
	"I'm gonna dream about the time when I'm with you\n",
	"When I go out (when I go out) well I know I'm gonna be\n",
	"I'm gonna be the man who goes along with you\n",
	"And when I come home (when I come home) yes I know I'm gonna be\n",
	"I'm gonna be the man who comes back home with you\n",
	"I'm gonna be the man who's coming home with you\n",
	"But I would walk 500 miles\n",
	"And I would walk 500 more\n",
	"Just to be the man who walks a thousand miles\n",
	"To fall down at your door\n",
	"Da da da (da da da)\n",
	"Da da da (da da da)\n",
	"Da da da dun diddle un diddle un diddle uh da\n",
	"Da da da (da da da)\n",
	"Da da da (da da da)\n",
	"Da da da dun diddle un diddle un diddle uh da\n",
	"Da da da (da da da)\n",
	"Da da da (da da da)\n",
	"Da da da dun diddle un diddle un diddle uh da\n",
	"Da da da (da da da)\n",
	"Da da da (da da da)\n",
	"Da da da dun diddle un diddle un diddle uh da\n",
	"And I would walk 500 miles\n",
	"And I would walk 500 more\n",
	"Just to be the man who walked a thousand miles\n",
	"To fall down at your door\n"
};

const char* VERLIEBEN_VERLOREN_VERGESSEN_VERZEIHN[45] = {
	"Du gingst von mir in einer Stunde\n",
	"Es war die Stunde Null\n",
	"Ich hatte meinen Tiefpunkt\n",
	"Du nahmst mir vieles krumm\n",
	"Auf einmal da war keiner mehr da\n",
	"Und half mir auch nicht du\n",
	"Jetzt liebst du halt 'nen anderen\n",
	"Und mein Herz schaut traurig zu\n",
	"Verlieben, verloren, vergessen, verzeihen\n",
	"Verdammt, war ich glücklich, verdammt, bin ich frei\n",
	"Ich hatte doch alles alles was zählt\n",
	"Aber ohne dich leben, jetzt ist es zu spät\n",
	"Verlieben, verloren, vergessen, verzeihen\n",
	"Verdammt, war ich glücklich, verdammt, bin ich frei\n",
	"Ich hatte doch alles alles was zählt\n",
	"Aber ohne dich leben, jetzt ist es zu spät\n",
	"Jetzt sitz' ich auf meinem Bett rum\n",
	"Hab die Kneipe hinter mir\n",
	"In meinem Kopf geht gar nichts mehr\n",
	"Mein Herz es braucht dich sehr\n",
	"Auf einmal da war keiner mehr da\n",
	"Und half mir auch nicht du\n",
	"Jetzt liebst du halt 'nen anderen\n",
	"Und mein Herz schaut traurig zu\n",
	"Verlieben, verloren, vergessen, verzeihen\n",
	"Verdammt, war ich glücklich, verdammt, bin ich frei\n",
	"Ich hatte doch alles alles was zählt\n",
	"Aber ohne dich leben, jetzt ist es zu spät\n",
	"Verlieben, verloren, vergessen, verzeihen\n",
	"Verdammt, war ich glücklich, verdammt, bin ich frei\n",
	"Ich hatte doch alles alles was zählt\n",
	"Aber ohne dich leben, jetzt ist es zu spät\n",
	"Verlieben, verloren, vergessen, verzeihen\n",
	"Verdammt, war ich glücklich, verdammt, bin ich frei\n",
	"Ich hatte doch alles alles was zählt\n",
	"Aber ohne dich leben, jetzt ist es zu spät\n",
	"Verlieben, verloren, vergessen, verzeihen\n",
	"Verdammt, war ich glücklich, verdammt, bin ich frei\n",
	"Ich hatte doch alles alles was zählt\n",
	"Aber ohne dich leben, jetzt ist es zu spät\n",
	"Verlieben, verloren, vergessen, verzeihen\n",
	"Verdammt, war ich glücklich, verdammt, bin ich frei\n",
	"Ich hatte doch alles alles was zählt\n",
	"Aber ohne dich leben, jetzt ist es zu spät\n",
	"Verlieben, verloren, vergessen, verzeihen\n"
};

const char* BIG_ENOUGH[63] = {
	"I've lived in lonely cities\n",
	"I've crossed deserts on camel back\n",
	"And I've filled the halls of folklore with things I'd rather we forget\n",
	"I could sweep you off the street so saying this is goddamn tough\n",
	"But this town might be big enough\n",
	"See, I reckon what you're saying\n",
	"But this dog's run every course\n",
	"I've roamed without my boots on\n",
	"I've raced without my horse\n",
	"And then I ate my horse's meat straight from my horse's bones\n",
	"'Cause this dog\n",
	"Must roam alone\n",
	"You could shoot me in the mountains\n",
	"In the cold fat rain\n",
	"(We could do it in the countryside\n",
	"As we walk the plain)\n",
	"It wouldn't give us any closure\n",
	"All cowboys need to trust\n",
	"That this town might be big enough\n",
	"For both of us\n",
	"Ah\n",
	"Ah\n",
	"Ah\n",
	"Ah\n",
	"Aah\n",
	"Ah\n",
	"Aah\n",
	"Well, I'd be a doggamn liar\n",
	"If I said this ain't a lonely town\n",
	"And what I wouldn't give\n",
	"To have a friend around\n",
	"We could trade in all our silver bullets\n",
	"And buy a patch of dust\n",
	"This town might just be big enough\n",
	"For all of us\n",
	"Ah\n",
	"Ah\n",
	"Everybody!\n",
	"This town!\n",
	"This world!\n",
	"Are you big enough?\n",
	"From Australia (ah) to America\n",
	"And Russia and China\n",
	"All of Asia\n",
	"Let me out\n",
	"Europe and Great Britain\n",
	"Oh Canada\n",
	"In Croatia and Serbia\n",
	"Kenya get it India\n",
	"It's serious in Syria\n",
	"Believe in us Bolivia\n",
	"We're Ghana be big enough\n",
	"For Africa, South Africa\n",
	"South Korea, North Korea\n",
	"Algeria, Nigeria\n",
	"Antarctica, Around the Equator\n",
	"Cuba, Indonesia\n",
	"Jamaica, we'll take ya\n",
	"To Florida and catch you later\n",
	"I'll catch you later\n",
	"Christianity, Islam, Judaism\n",
	"Let me out\n",
	"Are you big enough?\n"
};

const char* BITCONNECT[77] = {
	"Hey hey hey everybody my name is Carlos Matos And I am coming from New York City, New York Let me tell you guys that I am so excited, I am so happy I am really so thrilled to be right now, sharing this amazing, glorious Super, and exciting moment of my life with all of you guys And let me tell you that we are really changing the world as we know it The world is not anymore the way it used to be; Mmmm-Mmmm no no no\n",
	"\n",
	"Bit-con-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Ne Ne Ne Ne\n",
	"\n",
	"BITCONNEE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-ECT\n",
	"Wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu\n",
	"NE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE\n",
	"Wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu\n",
	"What?\n",
	"I LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOVE\n",
	"Bit-ConECT\n",
	"Yes!\n",
	"\n",
	"I am right now independently- financially independently I am saying to so many people who said That this was going to be a con-artist game That this was going to be a scammer game Hey, you're going to be losing all your money!\n",
	"I'm telling him 'Well, honey listen this is real!'\n",
	"Oh- No no no no\n",
	"That's uh scam\n",
	"That's uh scam\n",
	"That's uh scam\n",
	"\n",
	"We are coming and we are coming in waves We are starting and we are going to watch it go all over the world My wife still doesn't believe in me; What am I gonna to do?\n",
	"We are coming in waves\n",
	"What!?\n",
	"\n",
	"Hey hey hey\n",
	"Hey hey hey\n",
	"Hey hey hey\n",
	"\n",
	"Go-od morning, Good afternoon, Good evening To everyone from around the world This is Carlos Matos, Broadcasting live Directly from the Bronx, New York, USA Wassa Wassa Wassa Wassa Wassa Wassa Wassa Wassa What's up?\n",
	"\n",
	"BITCONNEE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-ECT\n",
	"Wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu\n",
	"NE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE\n",
	"Wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu\n",
	"\n",
	"EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-EEE-\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bitco\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Bit Bit\n",
	"Ne Ne Ne Ne\n",
	"\n",
	"BITCONNEE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-ECT\n",
	"Wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu\n",
	"NE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE-EE\n",
	"Wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu-wu\n",
	"What!?\n",
	"I LOOOUUUAAAOOOUUUOOOOOOOOOVE\n",
	"I LOOOUUUAAAOOOUUUOOOOOOOOOVE\n",
	"\n",
	"[Distorted, Wind Down]\n",
	"Bit-Con-EEEEEEEEEEEeeeeeeeeeeeect\n"
};

const char* NYAN_CAT[79] = {
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n",
	"Nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan nyan\n"
};

const char* OPERATING_SYSTEM_SONG[45] = {
	"Oh, I need to store my data\n",
	"Both right now and later on\n",
	"Speedy access and persistence are\n",
	"The qualities I want\n",
	"So there's random access memory\n",
	"And there's disk that I can use\n",
	"But to find my data in them\n",
	"Always makes me all confused\n",
	"\n",
	"Operating system\n",
	"Please handle that for me\n",
	"Lookup tables, clever scheduling\n",
	"For disk and memory\n",
	"\n",
	"Now my code runs fine in just one thread,\n",
	"but one is not enough\n",
	"So I tried to start another\n",
	"But the going there got tough\n",
	"If they both accessed a variable,\n",
	"They always failed to share\n",
	"One would clobber the other's changes\n",
	"While the other's unaware\n",
	"\n",
	"Operating system\n",
	"Please handle that for me\n",
	"With semaphores and monitors\n",
	"I get concurrency\n",
	"\n",
	"Though my code may work on my machine\n",
	"I now feel all alone\n",
	"I can't share my work with anyone\n",
	"Outside of my own home\n",
	"So I'll try to hook up wires\n",
	"From my friend's machine to mine, but\n",
	"The things we send are streams of bytes\n",
	"No reason and no rhyme\n",
	"\n",
	"Operating system\n",
	"Please handle that for me\n",
	"Standard protocols make sense of things\n",
	"Like TCP/IP\n",
	"Operating system\n",
	"Please handle that for me\n",
	"Thanks for helping me with everything\n",
	"Without you, where would I be?\n"
};

const char* SCHICKERIA[55] = {
	"Ja in Schwabing gibt's a Kneipen\n",
	"Die muss ganz was besondres sein\n",
	"Da lassens solche Leit\n",
	"Wie di und mi erst gar net nei\n",
	"\n",
	"In d'Schickeria, in d'Schickeria\n",
	"Jeder spielt'n Superstar\n",
	"Und sauft en Champus an der Bar\n",
	"In der Schickeria\n",
	"\n",
	"Schick-schick, Schick-schick, Schickeria\n",
	"Schick-schick, Schick-schick, Schickeria\n",
	"\n",
	"Ja mei, wie kommst denn du daher?\n",
	"A wenig ausgflippt musst scho sei\n",
	"Sonst last di der Gorilla\n",
	"An der Engangstür net nei\n",
	"\n",
	"In d'Schickeria, in d'Schickeria\n",
	"Jeder zieht sich ausgflippt o\n",
	"Weil er sonst net landen ko\n",
	"In der Schickeria\n",
	"\n",
	"\n",
	"Schick-schick, Schick-schick, Schickeria\n",
	"Schick-schick, Schick-schick, Schickeria\n",
	"\n",
	"Ja gestern hammer g'hascht\n",
	"Doch heutztag schnupft ma Kokain\n",
	"Und morn sitz ma in Stadelheim\n",
	"Aber Hauptsach mir san in\n",
	"\n",
	"In d'Schickeria, in d'Schickeria\n",
	"Jeder Morn der is a Star\n",
	"Und schnupft wia wuild das er was guilt\n",
	"In der Schickeria\n",
	"\n",
	"Schick-schick, Schick-schick, Schickeria\n",
	"Schick-schick, Schick-schick, Schickeria\n",
	"\n",
	"Ja in Schwabing gibt's a Kneipen\n",
	"Die muss ganz was besondres sein\n",
	"Da lassens solche Leit\n",
	"Wie di und mi erst gar net nei\n",
	"\n",
	"In d'Schickeria, in d'Schickeria\n",
	"Jeder spielt'n Superstar\n",
	"Und sauft en Champus an der Bar\n",
	"In der Schickeria\n",
	"\n",
	"\n",
	"Schick-schick, Schick-schick, Schickeria\n",
	"Schick-schick, Schick-schick, Schickeria\n",
	"Schick-schick, Schick-schick, Schickeria\n",
	"Schick-schick, Schick-schick, Schickeria\n"
};

const char* DER_KOMMISAR[83] = {
	"Alles klar, Herr Kommissar?\n",
	"Check it out Joe, ha\n",
	"\n",
	"Two, three, four\n",
	"Eins, zwei drei, na es is nix dabei\n",
	"Ja, wenn ich euch erzähl' die G'schicht\n",
	"Nichts desto trotz, ich bin das schon gewohn\n",
	"Im TV-Funk da läuft es nicht, cha\n",
	"\n",
	"Sie war jung das Herz so rein und weiß\n",
	"Und jede Nacht hat ihren Preis\n",
	"Sie sagt: \"Sugar sweet\"\n",
	"You gotta rappin' to the beat\n",
	"Ich verstehe, sie ist heiß\n",
	"Sie sagt: \"Babe, you know\"\n",
	"I miss my funky friends\n",
	"Sie meint Jack und Joe und Jill\n",
	"\n",
	"\n",
	"Mein Funkverständnis\n",
	"Ja das reicht zur Not\n",
	"Ich überreiß' was sie jetzt will\n",
	"Ich überleg bei mir\n",
	"Ihr Nas'n spricht dafür\n",
	"Währenddessen ich noch rauch'\n",
	"Die special places sind ihr wohl bekannt\n",
	"Ich mein, sie fährt ja U-Bahn auch\n",
	"\n",
	"Dort singen's\n",
	"Drah' di net um - oh, oh, oh\n",
	"Schau, schau, der Kommissar geht um - oh, oh, oh\n",
	"Er wird di anschau'n und du weißt warum\n",
	"Die Lebenslust bringt di um\n",
	"\n",
	"Alles klar, Herr Kommissar?\n",
	"Hey man, you man up\n",
	"You wanna buy some stuff, huh?\n",
	"Did you ever rap that thing Jack?\n",
	"So rap it to the beat\n",
	"\n",
	"Wir treffen Jill und Joe und dessen Bruder Hipp\n",
	"Und auch den Rest der coolen Gang\n",
	"Sie rappen hin, sie rappen her\n",
	"Dazwischen kratzen's ab die Wänd'\n",
	"\n",
	"Dieser Fall ist klar, lieber Herr Kommissar\n",
	"Auch wenn sie anderer Meinung sind\n",
	"Den Schnee auf dem wir alle talwärts fahren\n",
	"Kennt heute jedes Kind\n",
	"\n",
	"\n",
	"Jetzt das Kinderlied\n",
	"Drah di net um - oh, oh, oh\n",
	"Schau, schau, der Kommissar geht um - oh, oh, oh\n",
	"Er wird di anschauen und du weißt warum\n",
	"Die Lebenslust bringt di um\n",
	"Alles klar, Herr Kommissar?\n",
	"\n",
	"Hey man, you man up\n",
	"Cha cha cha cha cha cha cha\n",
	"Cha cha cha cha cha cha cha\n",
	"Cha cha cha cha cha cha cha\n",
	"Cha cha cha cha cha\n",
	"\n",
	"You wanna buy some stuff, man, huh?\n",
	"Cha cha cha cha cha cha cha\n",
	"Cha cha cha cha cha cha cha\n",
	"Hey man, you man up\n",
	"Cha cha cha cha cha cha cha\n",
	"Cha cha cha cha cha cha, aah\n",
	"\n",
	"Drah di net um\n",
	"Wenn er di anspricht und du weißt warum\n",
	"Der Kommissar geht um\n",
	"Er hat die Kraft und wir san klein und dumm\n",
	"Drah di net um - oh, oh, oh\n",
	"Schau, schau, der Kommissar geht um - oh, oh, oh\n",
	"\n",
	"Ah, check it out\n",
	"Drah di net um - oh, oh, oh\n",
	"Schau, schau, der Kommissar geht um - oh, oh, oh\n",
	"Drah di net um - oh, oh, oh\n",
	"Schau, schau, der Kommissar geht um - oh, oh, oh\n"
};

const char* STILL_ALIVE[49] = {
	"This was a triumph\n",
	"I'm making a note here, huge success\n",
	"It’s hard to overstate my satisfaction\n",
	"\n",
	"Aperture Science, we do what we must because we can\n",
	"For the good of all of us\n",
	"Except the ones who are dead\n",
	"\n",
	"But there's no sense crying over every mistake\n",
	"You just keep on trying 'till you run out of cake\n",
	"And the science gets done, and you make a neat gun\n",
	"For the people who are still alive\n",
	"\n",
	"I’m not even angry\n",
	"I'm being so sincere right now\n",
	"Even though you broke my heart and killed me\n",
	"\n",
	"And tore me to pieces\n",
	"And threw every piece into a fire\n",
	"As they burned it hurt because I was so happy for you\n",
	"\n",
	"Now these points of data make a beautiful line\n",
	"And we're out of beta, we're releasing on time\n",
	"So I'm GlaD I got burned, think of all the things we learned\n",
	"For the people who are still alive\n",
	"\n",
	"Go ahead and leave me\n",
	"I think I prefer to stay inside\n",
	"Maybe you'll find someone else to help you\n",
	"\n",
	"Maybe Black Mesa\n",
	"That was a joke\n",
	"Haha\n",
	"Fat chance\n",
	"Anyways this cake is great, it's so delicious and moist\n",
	"\n",
	"Look at me still talking when there's science to do\n",
	"When I look out there, it makes me GLaD I’m not you\n",
	"I’ve experiments to run, there is research to be done\n",
	"On the people who are still alive\n",
	"\n",
	"And believe me, I am still alive\n",
	"I'm doing science and I’m still alive\n",
	"I feel fantastic and I'm still alive\n",
	"\n",
	"While you're dying I'll be still alive\n",
	"And while you’re dead I will be still alive\n",
	"Still alive\n",
	"Still alive\n"
};

const char* WANT_YOU_GONE[39] = {
	"Well here we are again,\n",
	"It's always such a pleasure,\n",
	"Remember when you tried to kill me twice?\n",
	"Oh, how we laughed and laughed,\n",
	"Except I wasn't laughing,\n",
	"Under the circumstances I've been shockingly nice\n",
	"\n",
	"You want your freedom take it,\n",
	"That's what I'm counting on,\n",
	"I used to want you dead but,\n",
	"Now I only want you gone\n",
	"\n",
	"She was a lot like you,\n",
	"(Maybe not quite as heavy),\n",
	"Now little Caroline is in here too\n",
	"One day they woke me up,\n",
	"So I could live forever,\n",
	"It's such a shame the same will never happen to you\n",
	"\n",
	"\n",
	"You've got your short, sad life left,\n",
	"That's what I'm counting on,\n",
	"I'll let you get right to it,\n",
	"Now I only want you gone\n",
	"\n",
	"Goodbye, my only friend,\n",
	"Oh, did you think I meant you?\n",
	"That would be funny if it weren't so sad,\n",
	"Well you have been replaced,\n",
	"I don't need anyone now,\n",
	"When I delete you maybe\n",
	"I'll stop feeling so bad\n",
	"\n",
	"Go make some new disaster,\n",
	"That's what I'm counting on,\n",
	"You're someone else's problem,\n",
	"Now I only want you gone,\n",
	"Now I only want you gone,\n",
	"Now I only want you gone.\n"
};

const char* LOL_INTERNET[41] = {
	"(Uh, ah)\n",
	"\n",
	"Sie kommt aus dem Internet\n",
	"Und sie ist eine Frau\n",
	"Danach hab' ich lang gesucht\n",
	"Das Angebot ist mau\n",
	"\n",
	"Sie war so verständnisvoll\n",
	"Und mochte mich ganz gern\n",
	"Die ganze Nacht am Rechner sitzen\n",
	"Und sie war nicht fern, oh\n",
	"\n",
	"Internet, LOL, Internet\n",
	"DSL und World Wide Web\n",
	"Internet, LOL, Internet\n",
	"Web 2.0 [Zwei-Null] und Online-Chat\n",
	"Internet, LOL, Internet\n",
	"IRC und ICQ\n",
	"Internet, LOL, Internet\n",
	"\n",
	"\n",
	"Ich hab' drei Jahre nicht gefickt\n",
	"Ihr darum eine Mail geschickt\n",
	"Im Kühlschrank steht 'ne Kiste Bier\n",
	"Wir treffen uns heut' Nacht bei mir\n",
	"Es klingelt... an der Tür\n",
	"Ich hab sie... aufgemacht\n",
	"\n",
	"Melli17 [Melli siebzehn] ist ein Typ! (Uh, ah)\n",
	"Melli17 ist ein Typ! (melli17 hat mich angelogen, melli17 hat mich betrogen)\n",
	"Melli17 ist ein Typ! (Uh, o-o-oh)\n",
	"Melli17 ist ein Typ! (melli17 ist ein Mann, melli17 ist ein Mann, melli17 ist ein Mann)\n",
	"\n",
	"Internet, LOL, Internet\n",
	"DSL und World Wide Web\n",
	"Internet, LOL, Internet\n",
	"Web 2.0 und Online-Chat\n",
	"Internet, LOL, Internet\n",
	"IRC und ICQ\n",
	"Internet, LOL, Internet\n",
	"ROTFL, ROTFL\n"
};

const char* COMPUTER_ICH_BEFEHLE_DIR[67] = {
	"Computer, ich befehle dir!\n",
	"Berechne mir das Leben!\n",
	"Du hast immer Recht,\n",
	"Mein niemals müder Rechenknecht!\n",
	"\n",
	"Computer, ich befehle dir!\n",
	"Ich bin dein Gebieter!\n",
	"Maschine, so gehorche mir!\n",
	"Teile diese Zahl durch 4!\n",
	"\n",
	"(ich) 16\n",
	"(er) 4\n",
	"(ich) 28\n",
	"(er) 7\n",
	"(ich) 42\n",
	"(er) 10,5\n",
	"(ich) Globalisierung\n",
	"(er) Kann nicht berechnet werden\n",
	"\n",
	"He!\n",
	"Du wagst es dich zu widersetzen,\n",
	"Ungetüm aus wirren Drähten,\n",
	"Röhren und Kartoffelsnacks!\n",
	"Vergesse nie, ich bin dein Gott!\n",
	"Und ich bin Fachkraft für Elektroschrott!\n",
	"\n",
	"Sei mein Diener,\n",
	"Sei mein Sklave,\n",
	"Sei mein, in alle Ewigkeit!\n",
	"Sei mein Diener,\n",
	"Sei mein Sklave,\n",
	"Sei mein, in alle Ewigkeit!\n",
	"Gehöre mir!\n",
	"\n",
	"Computer, ich befehle dir!\n",
	"Berechne mir das Leben!\n",
	"Du hast immer Recht,\n",
	"Mein niemals müder Rechenknecht!\n",
	"\n",
	"Computer, ich befehle dir!\n",
	"Ich bin dein Gebieter!\n",
	"Maschine, so sei mir zu Nutze,\n",
	"Rechne mir die Quadratwurzel!\n",
	"\n",
	"(ich) 9\n",
	"(er) 3\n",
	"(ich) 324\n",
	"(er) 18\n",
	"(ich) Null!\n",
	"(er) NULL\n",
	"(ich) Kautschukbaum!\n",
	"(er) Kann nicht berechnet werden.\n",
	"\n",
	"He!\n",
	"Du wagst es dich zu widersetzen,\n",
	"Ungetüm aus wirren Drähten,\n",
	"Röhren und Kartoffelsnacks!\n",
	"Vergesse nie, ich bin dein Gott!\n",
	"Und ich bin Fachkraft für Elektroschrott!\n",
	"\n",
	"Sei mein Diener,\n",
	"Sei mein Sklave,\n",
	"Sei mein, in alle Ewigkeit!\n",
	"Sei mein Diener,\n",
	"Sei mein Sklave,\n",
	"Sei mein, in alle Ewigkeit!\n",
	"Gehöre mir!\n"
};

const char* SURFIN_BIRD[90] = {
	"A-well-a everybody's heard about the bird!\n",
	"Bird bird bird, b-bird's the word\n",
	"A-well-a bird bird bird, bird is the word\n",
	"A-well-a bird bird bird, well-a bird is the word\n",
	"A-well-a bird bird bird, b-bird's the word\n",
	"\n",
	"A-well-a bird bird bird, well-a bird is the word\n",
	"A-well-a bird, bird, b-bird's the word\n",
	"A-well-a bird bird bird, b-bird's the word\n",
	"A-well-a bird bird bird, well-a bird is the word\n",
	"A-well-a bird, bird, b-bird's the word\n",
	"\n",
	"A-well-a don't you know, about the bird?\n",
	"Well, everybody knows that the bird is the word!\n",
	"A-well-a bird, bird, b-bird's the bird\n",
	"\n",
	"A-well-a\n",
	"\n",
	"A-well-a everybody's heard, about the bird!\n",
	"Bird bird bird, b-bird's the word\n",
	"A-well-a bird bird bird, b-bird's the word\n",
	"\n",
	"\n",
	"A-well-a bird bird bird, b-bird's the word\n",
	"A-well-a bird, bird, b-bird's the word\n",
	"A-well-a bird bird bird, b-bird's the word\n",
	"A-well-a bird bird bird, b-bird's the word\n",
	"\n",
	"A-well-a bird bird bird, b-bird's the word\n",
	"A-well-a bird bird bird, b-bird's the word\n",
	"A-well-a don't you know, about the bird?\n",
	"Well! Everybody's talking about the bird!\n",
	"\n",
	"A-well-a bird, bird, b-bird's the bird\n",
	"A-well-a bird!\n",
	"\n",
	"Surfin\n",
	"Blr-blr-blr-blr-blr-blr-blr...\n",
	"\n",
	"Pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa pa\n",
	"Oom m-mow mow\n",
	"Pa pa oom mow m-mow\n",
	"Pa pa pa oom m-mow mow\n",
	"\n",
	"Pa pa oom mow m-mow\n",
	"Pa pa oom m-mow mow\n",
	"Pa pa oom mow m-mow\n",
	"Oom m-mow mow\n",
	"\n",
	"\n",
	"Pa pa oom mow m-mow\n",
	"Pa pa oom m-mow mow\n",
	"Pa pa oom mow m-mow\n",
	"Pa pa oom m-mow mow\n",
	"\n",
	"Pa pa oom mow m-mow\n",
	"Oom m-oom m-oom m-oom\n",
	"M-oom m-mow mow\n",
	"Pa pa oom mow m-mow\n",
	"\n",
	"Pa pa oom m-oom m-oom m-oom\n",
	"M-oom m-mow mow\n",
	"Pa pa oom mow m-mow\n",
	"\n",
	"Oom m-mow mow\n",
	"Pa pa oom mow m-mow\n",
	"Pa pa oom m-mow mow\n",
	"Pa pa oom mow m-mow\n",
	"Pa pa oom m-mow mow\n",
	"Oom mow m-mow\n",
	"Pa pa oom m-mow mow\n",
	"Oom mow m-mow\n",
	"Pa pa oom m-oom m-oom m-oom\n",
	"M-oom m-mow mow\n",
	"Oom m-oom m-oom m-oom\n",
	"M-oom m-mow mow\n",
	"Oom mow m-mow\n",
	"Pa pa oom mow m-mow\n",
	"Pa pa oom m-mow mow\n",
	"Oom mow m-mow\n",
	"Well-a don't you know, about the bird?\n",
	"Well! Everybody knows that the bird is the word!\n",
	"A-well-a bird, bird, b-bird's the bird\n",
	"A-well-a oom m-mow mow\n",
	"Pa pa oom mow m-mow\n",
	"Ba pa oom m-mow mow\n",
	"Oom mow m-mow\n",
	"Pa pa oom m-mow mow\n",
	"Oom mow m-mow\n",
	"Pa pa oom m-mow mow\n"
};

const struct song SONGS[NUM_SONGS] = {
	{"Never Gonna Give You Up", NEVER_GONNA_GIVE_YOU_UP, 56},
	{"Who Let the Dogs Out", WHO_LET_THE_DOGS_OUT, 79},
	{"What Is Love", WHAT_IS_LOVE, 69},
	{"Major Tom", MAJOR_TOM, 59},
	{"Looking for Freedom", LOOKING_FOR_FREEDOM, 52},
	{"Skandal Im Sperrbezirk", SKANDAL_IM_SPERRBEZIRK, 56},
	{"Danger Zone", DANGER_ZONE, 34},
	{"Scatman", SCATMAN, 98},
	{"I Like to Move It", I_LIKE_TO_MOVE_IT, 81},
	{"Tequila", TEQUILA, 3},
	{"Barbie Girl", BARBIE_GIRL, 58},
	{"Disco Pogo", DISCO_POGO, 51},
	{"Cheri Cheri Lady", CHERI_CHERI_LADY, 69},
	{"Boomerang", BOOMERANG, 61},
	{"99 Luftballons", NEUNUNDNEUNZIG_LUFTBALLONS, 41},
	{"Blue (Da Ba Dee)", BLUE_DA_BA_DEE, 43},
	{"Ocean Man", OCEAN_MAN, 18},
	{"Shout", SHOUT, 102},
	{"I'm Gonna Be (500 Miles)", I_M_GONNA_BE_500_MILES, 59},
	{"Verlieben, Verloren, Vergessen, Verzeih'n", VERLIEBEN_VERLOREN_VERGESSEN_VERZEIHN, 45},
	{"Big Enough", BIG_ENOUGH, 63},
	{"Bitconnect", BITCONNECT, 77},
	{"Nyan Cat", NYAN_CAT, 79},
	{"Operating System Song", OPERATING_SYSTEM_SONG, 45},
	{"Schickeria", SCHICKERIA, 55},
	{"Der Kommissar", DER_KOMMISAR, 83},
	{"Still Alive", STILL_ALIVE, 49},
	{"Want You Gone", WANT_YOU_GONE, 39},
	{"LOL, Internet", LOL_INTERNET, 41},
	{"Computer Ich Befehle Dir", COMPUTER_ICH_BEFEHLE_DIR, 67},
	{"Surfin Bird", SURFIN_BIRD, 90}
};